# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-26 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('photo', models.CharField(max_length=80, verbose_name='Photo')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
            ],
            options={
                'get_latest_by': '-created',
                'ordering': ['-created'],
            },
        ),
    ]
